services:
  synapse:
    image: localhost:5001/synapse:${SERVER_TAG:-latest}
    build: .
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=dev
      - DB_HOST=synapse-mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=123456
      - DB_DATABASE=synapse
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - synapse-net
    restart: unless-stopped

  synapse-web:
    image: localhost:5001/synapse-web:${WEB_TAG:-latest}
    build:
      context: ../Synapse-Web
    ports:
      - "3080:80"
    depends_on:
      - synapse
    networks:
      - synapse-net
    restart: unless-stopped

networks:
  synapse-net:
    external: true
